version: '3'

services:
  cockroachdb:
    image: cockroachdb/cockroach:v21.1.10
    ports:
      - "26257:26257"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    command: start-single-node --insecure

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cockroachdb
    environment:
      - DB_HOST=cockroachdb
    ports:
      - "8080:8080"

volumes:
  cockroach-data:
